# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/monitor-http-request"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/ble-sensors-2-mqtt"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/data-panel-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/data-panel-autoload"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    target-branch: "dev"
    directory: "/data-panel-front"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/dns-updater"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/monitor-heartbeat-control"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/monitor-heartbeat-request"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/hue-inbound"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/hue-sensors-alerts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/logger"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/hue-logic-pool"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/logic-pool-mqtt"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/logic-pool-time"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/notification-message"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/mqtt-2-bigquery"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/hue-outbound"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/task-scheduler"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/telegram-bot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/notification-voice"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  # Docker
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/monitor-http-request"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/ble-sensors-2-mqtt"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/data-panel-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/data-panel-autoload"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/data-panel-front"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/dns-updater"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/monitor-heartbeat-control"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/monitor-heartbeat-request"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/hue-inbound"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/hue-sensors-alerts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/logger"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/hue-logic-pool"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/logic-pool-mqtt"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/logic-pool-time"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/notification-message"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/mqtt-2-bigquery"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/hue-outbound"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/task-scheduler"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/telegram-bot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/notification-voice"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

