version: "3.4"

services:
  # DNS updater
  dns-updater:
    image: ghcr.io/kikeelectronico/dns-updater:latest
    container_name: dns-updater
    restart: always
    network_mode: "host"
    env_file:
     - .env
    depends_on:
      - message-alert

  # Heartbeat request
  heartbeat-request:
    image: ghcr.io/kikeelectronico/heartbeat-request:latest
    container_name: heartbeat-request
    restart: always
    network_mode: "host"
    env_file:
     - .env
    depends_on:
      - message-alert

  # Heartbeat monitor
  heartbeat-monitor:
    image: ghcr.io/kikeelectronico/heartbeat-monitor:latest
    container_name: heartbeat-monitor
    restart: always
    network_mode: "host"
    env_file:
     - .env
    depends_on:
      - message-alert

  # Big Query connector
  mqtt-2-bigquery:
    image: ghcr.io/kikeelectronico/mqtt-2-bigquery:latest
    container_name: mqtt-2-bigquery
    restart: always
    network_mode: "host"
    env_file:
     - .env
    depends_on:
      - message-alert

  # MQTT 2 Hue
  mqtt-2-hue:
    image: ghcr.io/kikeelectronico/mqtt-2-hue:latest
    container_name: mqtt-2-hue
    restart: always
    network_mode: "host"
    env_file:
     - .env
    depends_on:
      - message-alert

  # Hue 2 MQTT
  hue-2-mqtt:
    image: ghcr.io/kikeelectronico/hue-2-mqtt:latest
    container_name: hue-2-mqtt
    restart: always
    network_mode: "host"
    env_file:
     - .env

  # Logic pool hue
  logic-pool-hue:
    image: ghcr.io/kikeelectronico/logic-pool-hue:latest
    container_name: logic-pool-hue
    restart: always
    network_mode: "host"
    env_file:
     - .env
      
  # Logic pool time
  logic-pool-time:
    image: ghcr.io/kikeelectronico/logic-pool-time:latest
    container_name: logic-pool-time
    restart: always
    network_mode: "host"
    env_file:
     - .env
    depends_on:
      - message-alert

  # Logic pool mqtt
  logic-pool-mqtt:
    image: ghcr.io/kikeelectronico/logic-pool-mqtt:latest
    container_name: logic-pool-mqtt
    restart: always
    network_mode: "host"
    env_file:
     - .env
    depends_on:
      - message-alert

  # Voice alert
  voice-alert:
    image: ghcr.io/kikeelectronico/voice-alert:latest
    container_name: voice-alert
    restart: always
    network_mode: "host"
    env_file:
     - .env
    volumes:
     - creds:/app/creds

  # Message alert
  message-alert:
    image: ghcr.io/kikeelectronico/message-alert:latest
    container_name: message-alert
    restart: always
    network_mode: "host"
    env_file:
     - .env
    volumes:
     - creds:/app/creds

  # Alert system, request
  alert-system-request:
    image: ghcr.io/kikeelectronico/alert-system-request:latest
    container_name: alert-system-request
    restart: always
    network_mode: "host"
    env_file:
     - .env
    volumes:
     - creds:/app/creds
    depends_on:
      - voice-alert
      - message-alert

  # Task scheduler
  task-scheduler:
    image: ghcr.io/kikeelectronico/task-scheduler:latest
    container_name: task-scheduler
    restart: always
    network_mode: "host"
    env_file:
     - .env
    depends_on:
      - voice-alert
      - message-alert

  # Bot
  telegram-bot:
    image: ghcr.io/kikeelectronico/telegram-bot:latest
    container_name: telegram-bot
    restart: always
    network_mode: "host"
    volumes:
      - creds:/app/creds

  # Data panel, front
  data-panel-front:
    image: ghcr.io/kikeelectronico/data-panel-front:latest
    container_name: data-panel-front
    restart: always
    ports:
      - "81:80"
    depends_on:
      - data-panel-api

  # Data panel, API REST
  data-panel-api:
    image: ghcr.io/kikeelectronico/data-panel-api:latest
    container_name: data-panel-api
    restart: always
    network_mode: "host"
    expose:
      - "8000"
    env_file:
     - .env

  # Data panel, autoload
  data-panel-autoload:
    image: ghcr.io/kikeelectronico/data-panel-autoload:latest
    container_name: data-panel-autoload
    restart: always
    network_mode: "host"
    depends_on:
      - data-panel-front

volumes:
  creds:
