name: Build and publish Alert system mqtt

on:
  push:
    branches: [ main ]
    paths:
      - "alert-system-mqtt/**"
  pull_request:
    branches: [ main ]
    paths:
      - "alert-system-mqtt/**"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  alert-system-mqtt:
    name: Build and publish the service
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: alert-system-mqtt
          file: alert-system-mqtt/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/kikeelectronico/alert-system-mqtt:latest