name: Build Data Panel Front

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "data-panel-front/**"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  data-panel-front:
    name: Build and publish the frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: data-panel-front
          file: data-panel-front/Dockerfile
          platforms: linux/amd64 #, linux/arm/v7, linux/arm64/v8
          push: true
          tags: ${{ env.REGISTRY }}/kikeelectronico/data-panel-front:latest
