name: Production

on:
    workflow_call:
      inputs:
        service:
          required: true
          type: string
  
env:
  REGISTRY: ghcr.io

jobs:
  paths-filter:
    name: Paths filters
    runs-on: ubuntu-latest
    outputs:
        changed: ${{ steps.filter.outputs.changed }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
            changed:
            - "alert-system-request/**"

  alert-system-request:
    name: Build alert-system-request
    runs-on: ubuntu-latest
    needs: paths-filter
    permissions:
      contents: read
      packages: write
    env:
      SERVICE_NAME: "alert-system-request"
    if: needs.paths-filter.outputs.changed == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.SERVICE_NAME }}
          file: ${{ env.SERVICE_NAME }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/kikeelectronico/${{ env.SERVICE_NAME }}:latest