name: Build and publish Logic pool mqtt

on:
  push:
    branches: [ main ]
    paths:
      - "logic-pool-mqtt/**"
  pull_request:
    branches: [ main ]
    paths:
      - "logic-pool-mqtt/**"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  mqtt-2-bigquery:
    name: Build and publish the service
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: logic-pool-mqtt
          file: logic-pool-mqtt/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/kikeelectronico/logic-pool-mqtt:latest