name: Build service - Reusable

on:
    workflow_call:
        inputs:
            service:
                required: true
                type: string
            registry:
                required: true
                type: string
        secrets:
            PERSONAL_ACCESS_TOKEN:
                required: true
            actor:
                required: true
  
jobs:
  path-filter:
    name: Filter ${{ inputs.service }}
    runs-on: ubuntu-latest
    outputs:
        changed: ${{ steps.filter.outputs.changed }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
            changed:
            - "${{ inputs.service }}/**"

  build:
    name: Build ${{ inputs.service }}
    runs-on: ubuntu-latest
    needs: path-filter
    permissions:
      contents: read
      packages: write
    if: needs.path-filter.outputs.changed == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{ inputs.registry }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.service }}
          file: ${{ inputs.service }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ inputs.registry }}/kikeelectronico/${{ inputs.service }}:latest