name: Data Panel Autoload

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "data-panel-autoload/**"

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
  
env:
  REGISTRY: ghcr.io

jobs:
  build-publish:
    name: Build and publish the autoload service
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: data-panel-autoload
          file: data-panel-autoload/Dockerfile
          platforms: linux/amd64 #, linux/arm/v7, linux/arm64/v8
          push: true
          tags: ${{ env.REGISTRY }}/kikeelectronico/data-panel-autoload:latest
  deploy:
    name: Deploy to the server
    runs-on: ubuntu-latest
    needs: build-publish
    steps:
      - name: Request update
        run: |
          curl --location '${{ secrets.DIP_BASE_URL }}/images/pull' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --data-urlencode 'token=${{ secrets.DIP_TOKEN }}' \
          --data-urlencode 'restart_containers=true' \
          --data-urlencode 'image=ghcr.io/kikeelectronico/data-panel-autoload:latest'