name: Dev test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ dev ]

# concurrency: 
#   group: ${{ github.workflow }}

jobs:
  build:
    name: Build
    strategy:
      matrix:
        service:
          - alert-system-request
          - ble-sensors-2-mqtt
          - data-panel-api
          - data-panel-autoload
          - data-panel-front
          - dns-updater
          - heartbeat-monitor
          - heartbeat-request
          - hue-2-mqtt
          - hue-sensors-alerts
          - logger
          - logic-pool-hue
          - logic-pool-mqtt
          - logic-pool-time
          - message-alert
          - mqtt-2-bigquery
          - mqtt-2-hue
          - telegram-bot
          - voice-alert
          - task-scheduler
    uses: ./.github/workflows/build-service.yml
    with:
      registry: ghcr.io
      service: ${{ matrix.service }}
      tag: dev
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
      actor: ${{ github.actor }}