name: Dev test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        service:
          - bigquery-outbound
          - ble-inbound
          - data-panel-api
          - data-panel-front
          - dns-updater
          - hue-inbound
          - hue-logic-pool
          - hue-outbound
          - hue-sensors-alerts
          - logger
          - logic-pool-mqtt
          - logic-pool-time
          - monitor-heartbeat-control
          - monitor-heartbeat-request
          - monitor-http-request
          - notification-message
          - notification-voice
          - task-scheduler
          - telegram-bot
    uses: ./.github/workflows/build-service.yml
    with:
      service: ${{ matrix.service }}
      tag: dev
    secrets:
      REGISTRY: ${{secrets.REGISTRY}}
      REGISTRY_REPO: ${{secrets.REGISTRY_REPO}}
      GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
