name: Logic pool mqtt

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "logic-pool-mqtt/**"

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
  
env:
  REGISTRY: ghcr.io

jobs:
  build-publish:
    name: Build and publish the service
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: logic-pool-mqtt
          file: logic-pool-mqtt/Dockerfile
          platforms: linux/amd64 #, linux/arm/v7, linux/arm64/v8
          push: true
          tags: ${{ env.REGISTRY }}/kikeelectronico/logic-pool-mqtt:latest
  deploy:
    name: Deploy to the server
    runs-on: ubuntu-latest
    needs: build-publish
    steps:
      - name: Request update
        run: |
          curl --location --request POST '${{ secrets.DIP_URL }}' \
          --header 'Authorization: Bearer ${{ secrets.DIP_TOKEN }}'