name: Prod - test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
  
env:
  REGISTRY: ghcr.io

jobs:
  paths-filter:
    name: Paths filters
    runs-on: ubuntu-latest
    outputs:
      alert-system-request: ${{ steps.filter.outputs.alert-system-request }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          alert-system-request:
            - "alert-system-request/**"

  alert-system-request:
    name: Build and publish alert-system-request
    runs-on: ubuntu-latest
    needs: paths-filter
    permissions:
      contents: read
      packages: write
    if: needs.paths-filter.outputs.alert-system-request == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: alert-system-request
          file: alert-system-request/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/kikeelectronico/alert-system-request:latest
