name: Production test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
  
env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build
    strategy:
      matrix:
        service: ["alert-system-request"]
    uses: ./.github/workflows/build-service.yml
    with:
      service: ${{ matrix.service }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      actor: ${{ github.actor }}
