name: Production

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      matrix:
        service:
          - alert-system-request
          - ble-sensors-2-mqtt
          - data-panel-api
          - data-panel-autoload
          - data-panel-front
          - dns-updater
          - heartbeat-monitor
          - heartbeat-request
          - hue-2-mqtt
          - logger
          - logic-pool-hue
          - logic-pool-mqtt
          - logic-pool-time
          - message-alert
          - mqtt-2-bigquery
          - mqtt-2-hue
          - telegram-bot
          - voice-alert
          - task-scheduler
    uses: ./.github/workflows/build-service.yml
    with:
      registry: ghcr.io
      service: ${{ matrix.service }}
      tag: latest
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      actor: ${{ github.actor }}

  deploy:
    name: Deploy to production environment
    runs-on: ubuntu-latest
    needs: 
      - build
    if: ${{ always() && !failure() && !cancelled() }}
    steps:
      - name: Request update
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DIP_URL }}
          method: "POST"
          bearerToken: ${{ secrets.DIP_TOKEN }}